name: Cross-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment (Linux/macOS)
        if: runner.os != 'Windows'
        run: sudo apt-get update && sudo apt-get install -y build-essential || true

      - name: Set up build environment (Windows)
        if: runner.os == 'Windows'
        run: choco install make

      - name: Compile project
        run: make

      - name: Run tests
        run: make test
