name: Cross-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer les dépendances nécessaires (Linux/macOS)
      - name: Set up build environment (Linux/macOS)
        if: runner.os != 'Windows'
        run: sudo apt-get update && sudo apt-get install -y build-essential || true

      # Installer Make sur Windows
      - name: Set up build environment (Windows)
        if: runner.os == 'Windows'
        run: choco install make

      # Compiler le projet et exécuter les tests dans le répertoire "Version 1.0/easysave"
      - name: Compile and test project
        run: |
          cd "Version 1.0/easysave"   # Changer de répertoire
          make                        # Compiler le projet
          make test                   # Lancer les tests
