name: Build and Deploy EasySave

on:
  push:
    branches:
      - main  # Déclenche le pipeline sur les commits vers la branche principale
  pull_request:
    branches:
      - main  # Déclenche le pipeline lors de la création d'une PR vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest  # Vous pouvez aussi utiliser windows-latest ou macos-latest si nécessaire

    steps:
    # Checkout le code source du repo
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup .NET (si vous travaillez avec un projet .NET par exemple)
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'  # Changez la version si nécessaire

    # Installer les dépendances du projet (si applicable)
    - name: Restore dependencies
      run: |
        cd "Genie_logiciel/Version 1.0/easysave"
        dotnet restore

    # Construire le projet
    - name: Build project
      run: |
        cd "Genie_logiciel/Version 1.0/easysave"
        dotnet build

    # Exécuter les tests (si vous avez des tests unitaires)
    - name: Run tests
      run: |
        cd "Genie_logiciel/Version 1.0/easysave"
        dotnet test

    # Publier l'artefact (si vous voulez publier une version après un build)
    - name: Publish
      run: |
        cd "Genie_logiciel/Version 1.0/easysave"
        dotnet publish -c Release -o ./publish
        # Déployer ou copier les fichiers publiés selon vos besoins.
