name: Build and Deploy EasySave

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser windows-latest ou macos-latest selon votre environnement

    steps:
      # Checkout le code source du repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Vérification de la structure des répertoires après modification
      - name: List directory contents
        run: |
          ls -al
          ls -al "Genie_logiciel"
          ls -al "Genie_logiciel/Version1.0"
          ls -al "Genie_logiciel/Version1.0/easysave"

      # Setup .NET (si vous travaillez avec un projet .NET)
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'  # Changez la version si nécessaire

      # Restaurer les dépendances
      - name: Restore dependencies
        run: |
          cd "${GITHUB_WORKSPACE}/Genie_logiciel/Version1.0/easysave"
          dotnet restore

      # Construire le projet
      - name: Build project
        run: |
          cd "${GITHUB_WORKSPACE}/Genie_logiciel/Version1.0/easysave"
          dotnet build

      # Exécuter les tests (si vous avez des tests unitaires)
      - name: Run tests
        run: |
          cd "${GITHUB_WORKSPACE}/Genie_logiciel/Version1.0/easysave"
          dotnet test

      # Publier l'artefact (si vous voulez publier une version après un build)
      - name: Publish
        run: |
          cd "${GITHUB_WORKSPACE}/Genie_logiciel/Version1.0/easysave"
          dotnet publish -c Release -o ./publish
